services:
  pythonapp:
    build:
      context: .
    env_file: .env
    command: sh -c "sleep 10s; python /app/src/main.py /app/data/students.json /app/data/rooms.json --format json --output_name output"
    depends_on:
      - mysql_db

  mysql_db:
    build:
      context: ./mysql-init
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - '3307:3306'
